# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('mail', models.CharField(blank=True, max_length=200)),
                ('invoice', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('paper_id', models.CharField(blank=True, max_length=50)),
                ('stay', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
