# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enter_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='out_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
