# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20170809_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='register_number',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
