# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_auto_20170811_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
