# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0008_auto_20170811_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(default='', max_length=60, primary_key=True)),
                ('mail', models.CharField(max_length=200, null=True)),
                ('invoice', models.CharField(max_length=200, null=True)),
                ('tax_id', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('user_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=50, null=True)),
                ('stay', models.CharField(max_length=20, null=True)),
                ('m_name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('enter_date', models.CharField(max_length=100, null=True)),
                ('out_date', models.CharField(max_length=100, null=True)),
                ('register_number', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
