# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0011_auto_20170811_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enter_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='out_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
