# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0012_auto_20170811_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_number',
            field=models.CharField(blank=True, default=10000, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
