# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0013_auto_20170811_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enter_date',
        ),
        migrations.AddField(
            model_name='user',
            name='in_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
