# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0014_auto_20170811_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_number',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
